### ISSUE TITLE
Historias de Usuario y criterios de aceptación

### ISSUE THREAD

**Issue by KatherineGutierrezBustamante** [CarlosBe0305/Equipo1_FAZ_PPI2020#14]

**Comment by CarlosBe0305** [comment]
![Criterios de Aceptación_1](https://user-images.githubusercontent.com/55889668/88742570-2cd01780-d108-11ea-8f51-781c2009dac2.png)
![Criterios de Aceptación_2](https://user-images.githubusercontent.com/55889668/88742571-2d68ae00-d108-11ea-862a-8a7437d1c92c.png)
![Criterios de Aceptación_3](https://user-images.githubusercontent.com/55889668/88742573-2e014480-d108-11ea-8e1a-ea5470ff039a.png)
![Criterios de Aceptación_4](https://user-images.githubusercontent.com/55889668/88742574-2e014480-d108-11ea-868b-63c23d7ce999.png)
![Criterios de Aceptación_5](https://user-images.githubusercontent.com/55889668/88742577-2e99db00-d108-11ea-84f4-8de767b70299.png)
![Historias de Usuario](https://user-images.githubusercontent.com/55889668/88742579-2e99db00-d108-11ea-9a1f-6acc5f27acd7.png)
