### ISSUE TITLE
Mapas de Historias de usuario

### ISSUE THREAD

**Issue by KatherineGutierrezBustamante** [CarlosBe0305/Equipo1_FAZ_PPI2020#15]

**Comment by mariapaulinarios** [comment]
![mapa](https://user-images.githubusercontent.com/66378453/88744587-69ead880-d10d-11ea-8f60-28aa590ef807.PNG)

**Comment by CarlosBe0305** [comment]
![Mapa de Historias](https://user-images.githubusercontent.com/55889668/88864769-8c432b80-d1cb-11ea-960b-ea6dc75d4ca1.PNG)
