### ISSUE TITLE
Prototipo de alta fidelidad con navegabilidad

### ISSUE THREAD

**Issue by KatherineGutierrezBustamante** [CarlosBe0305/Equipo1_FAZ_PPI2020#16]

**Comment by mariapaulinarios** [comment]
![Bumpy 02](https://user-images.githubusercontent.com/66378453/88740923-f0022180-d103-11ea-8033-03c7cf0dfaf7.png)
![Bumpy 1](https://user-images.githubusercontent.com/66378453/88740817-b92c0b80-d103-11ea-951e-62f0206719e4.PNG)
![Bumpy 2](https://user-images.githubusercontent.com/66378453/88740827-bdf0bf80-d103-11ea-9f9f-7821f6519f6d.PNG)
![Bumpy 3](https://user-images.githubusercontent.com/66378453/88740850-c77a2780-d103-11ea-89e0-b5ff4c59d6e3.PNG)

**Comment by mariapaulinarios** [comment]
![p5](https://user-images.githubusercontent.com/66378453/88855631-c820c580-d1b8-11ea-87fc-68c77add133a.PNG)
![p5 1](https://user-images.githubusercontent.com/66378453/88855636-cbb44c80-d1b8-11ea-8072-44351c27d12a.PNG)

**Comment by mariapaulinarios** [comment]
![MapaF1](https://user-images.githubusercontent.com/66378453/90641066-66231100-e1f6-11ea-9ac7-a4e9fd5cc356.PNG)
![MapaF2](https://user-images.githubusercontent.com/66378453/90641089-6d4a1f00-e1f6-11ea-82a3-70d439ff8217.PNG)
![MapaF3](https://user-images.githubusercontent.com/66378453/90641108-73400000-e1f6-11ea-8023-272ac77fb0f1.PNG)

**Comment by CarlosBe0305** [comment]
![Mapa de Navegabilidad](https://user-images.githubusercontent.com/55889668/90646236-9c638f00-e1fc-11ea-8b28-89c31a1ec495.png)
